# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
"""..."""
import sys
from PyQt5 import QtWidgets
from Can import CanWidget
from MainDesigner import Ui_MainWindow


# !!! lineEdit prefix okuyup write motorola fonksiyonlarına gondermemisim unutmmusum

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    """main windows class derived main_designer.py"""

    def __init__(self):
        super(MainWindow, self).__init__()
        self.setupUi(self)
        self.can = CanWidget(self) #main window sent can widget for return point

        self.actionOpen.triggered.connect(self.open_can)

    def open_can(self):
        """Open CAN dbc and display it on the GUI"""
        self.hide()
        self.can.showNormal()
        return

    def closeEvent(self, event):
        """ Display a confirmation dialog before closing the window"""
        reply = QtWidgets.QMessageBox.question(
            self,
            "Confirm",
            "Are you sure you want to close the window?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
            QtWidgets.QMessageBox.No,
        )
        if reply == QtWidgets.QMessageBox.Yes:
            # Close and destroy the CanWidget instance
            self.can.destroy()
            # Close the main window
            event.accept()
            app.quit()
        else:
            # Do not close the main window
            event.ignore()


if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    window = MainWindow()
    window.setStyleSheet("background-color: white")
    window.showNormal()
    sys.exit(app.exec_())
