# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
""" etc """
from Can import CanWidget
from PyQt5 import QtWidgets
from MainDesigner import Ui_MainWindow


# lineEdit prefix okuyup write motorola intel fonksiyonlarına gondermemisim unutmmusum
#
class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    """main windows class derived main_designer.py"""

    def __init__(self):
        super(MainWindow, self).__init__()
        self.setupUi(self)
        self.can = CanWidget()

        self.actionOpen.triggered.connect(self.open_can)

    def open_can(self):
        """Open CAN dbc and display it on the GUI"""
        self.can.showNormal()
        return


if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    window = MainWindow()
    window.setStyleSheet("background-color: white")
    window.showNormal()
    app.exec_()
