# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main_designer import Ui_MainWindow
from Can import Can_Widget

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setupUi(self)
        self.can = Can_Widget()
        
        self.actionOpen.triggered.connect(self.open_can)

    
    def open_can(self):
        self.can.showNormal()




app = QtWidgets.QApplication([])
window = MainWindow()
window.setStyleSheet("background-color: white")
# window.showFullScreen()
window.showNormal()
app.exec_()
